server:
  port: 8081
spring:
  application:
    name: service-celulares
  mvc:
    pathmatch:
      matching-strategy: ANT_PATH_MATCHER
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka
